### ISSUE TITLE
Collectd error: Failed to open file "/sys/class/thermal/thermal_zone0/temp": No such file or directory.

### ISSUE THREAD

**Issue by jacotec** [sdr-enthusiasts/docker-tar1090#154]
First of all thank you for providing this great docker solution!

Unfortunately I'm periodically getting these errors and i.e. replay does not work:

```
tar1090  | [2023-11-30 16:16:05.667][collectd] [error] table plugin: Failed to open file "/sys/class/thermal/thermal_zone0/temp": No such file or directory.
tar1090  | [2023-11-30 16:16:05.667][collectd] [notice] read-function of plugin `table' failed. Will suspend it for 240.000 seconds. 
```

I don't see an issue in my docker-compose:

```
version: "3.8"

services:
  tar1090:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    environment:
      - TZ=Europe/Berlin
      - BEASTHOST=10.0.1.90
      - MLATHOST=10.0.1.90
      - LAT=[redacted]
      - LONG=[redacted]
    volumes:
      - /opt/adsb/tar1090/globe_history:/var/globe_history
      - /opt/adsb/tar1090/timelapse1090:/var/timelapse1090
      - /opt/adsb/tar1090/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
    # - /run/airspy_adsb:/run/airspy_adsb
    ports:
      - 8078:80
    tmpfs:
      - /run:exec,size=64M
      - /var/log

```
